services:
  backend1:
    build: ./backend
    ports:
      - "3000:3000" 
    networks:
      - PayZap
    environment:
      MONGO_URI: mongodb://mongo:27017/paytm  
    depends_on:
      - mongodb
  
  backend2:
    build: ./backend
    ports:
      - "3001:3000"  
    networks:
      - PayZap
    environment:
      MONGO_URI: mongodb://mongo:27017/paytm  
    depends_on:
      - mongodb 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - PayZap
    environment:
      REACT_APP_API_URL: http://backend:3000 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - PayZap
    volumes:
      - mongo-data:/data/db  

networks:
  PayZap:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
